---
title: "NYC Restaraunt Ratings"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
data("rest_inspec")
```


Column {data-width=650}
-----------------------------------------------------------------------

### Number of restaraunt ratings by neighborhood

```{r chartA}
rest_inspec %>% 
  filter(boro != "Missing") %>% 
  count(boro) %>% 
  mutate(boro = fct_reorder(boro, n)) %>% 
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar") %>% 
  layout(
      xaxis = list(title = "neighborhood"), 
      yaxis = list(title = "count")
      )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Restaraunt ratings by neighborhood

```{r chartB}
rest_inspec %>% 
  mutate(boro = fct_reorder(boro, score)) %>% 
  sample_n(1000) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box",
          colors = "Set2") %>% 
  layout(
      xaxis = list(title = "neighborhood"), 
      yaxis = list(title = "score")
      )
```

### Restaraunt ratings by inspection date with name and grade

```{r chartC}
rest_inspec  %>% 
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>%
  mutate(text_label = str_c("Name: ", dba, '\nGrade: ', grade)) %>% 
  sample_n(1000) %>% 
  plot_ly(
    x = ~score, y = ~inspection_date, type = "scatter", mode = "markers",
    color = ~grade, text = ~text_label, alpha = 0.75) %>% 
  layout(yaxis = list(
      type = 'date',
      range = c("2014","2017"))) %>% 
  layout(
      xaxis = list(title = "score"), 
      yaxis = list(title = "inspection date")
      )
```


