---
title: "Plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r data, include = FALSE}
data("rest_inspec")


rest_inspec =
  rest_inspec %>%
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro))

```

```{r data2, include = FALSE}
rest_inspec %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  spread(key = grade, value = n)
```


```{r grade_bar, echo=FALSE}
grade_bar = 
  rest_inspec %>% 
    ggplot(aes(x = boro, fill = grade)) +
    geom_bar(position = "dodge") +
    theme_minimal() 
    

ggplotly(grade_bar)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r grade_scatter, echo = FALSE}
grade_scatter = 
  rest_inspec %>%
  filter(boro == "Manhattan", 
         critical_flag == "Critical", 
         ) %>% 
  sample_n(100) %>%
  mutate(text_label = str_c(dba, violation_description)) %>% 
  ggplot(aes(x = score, y = inspection_date, text = text_label)) +
  geom_point(aes(color = grade), alpha = 0.75) +
  viridis::scale_color_viridis(name = "grade", discrete = TRUE) +
  coord_cartesian() +
  theme_minimal() 

ggplotly(grade_scatter)
```

### Chart C

```{r}

```
